### PR TITLE
Feature/add wojnarowicz

### PR DESCRIPTION
**Pull request by eshadatta**
Referencing #199. Thanks to your feedback, @da70 and @jgpawletko, I have re-factored the Wojnarowicz code. However, I was attempting to use the rspec/rake tests to see if I could test the json api for the requisite fields for Primo, but failed. I kept getting an error: 
`undefined method get for #<Class:0x007ff7d1839188> (NoMethodError)`
It's just a simple test to start with. I have commented that out [here](https://github.com/NYULibraries/ichabod/compare/feature/add_wojnarowicz?expand=1#diff-285f640067c12f51f2f580c20e7819a2R33). I'll keep working on getting the rspec to work but this is again(for me) balancing the time it took to get the code working and the time it's taking me to get the test working. If anyone from @NYULibraries/hydra including, of course, Joe and David, has feedback about the non-functioning test or the rest of the code, I'd really appreciate it. Thanks and have a great break everyone.

### CODE REVIEW

**Comment by eshadatta** [comment]
@NYULibraries/hydra : I'm getting a strange error in the builds: 
>$ bundle install --without development
Fetching source index from https://rubygems.org/
Fetching git://github.com/binarylogic/authlogic.git
Fetching git://github.com/barnabyalter/authpds.git
Fetching git://github.com/barnabyalter/authpds-nyu.git
Fetching git://github.com/barnabyalter/exlibris-aleph.git
fatal: Could not parse object '216a72a2cc40d6b0263e4963ae77138c6fd536e9'.
Git error: command `git reset --hard 216a72a2cc40d6b0263e4963ae77138c6fd536e9`
in directory
/home/travis/.rvm/gems/ruby-2.1.3/bundler/gems/exlibris-aleph-216a72a2cc40 has
failed.
If this error persists you could try removing the cache directory
'/home/travis/.rvm/gems/ruby-2.1.3/cache/bundler/git/exlibris-aleph-8c158a3cae6b9151bfb0cea18a61997a27b64ff5'
The command "eval bundle install --without development" failed. Retrying, 2 of 3.
Fetching source index from https://rubygems.org/
Updating git://github.com/barnabyalter/exlibris-aleph.git
fatal: Could not parse object '216a72a2cc40d6b0263e4963ae77138c6fd536e9'.
Git error: command `git reset --hard 216a72a2cc40d6b0263e4963ae77138c6fd536e9`
in directory
/home/travis/.rvm/gems/ruby-2.1.3/bundler/gems/exlibris-aleph-216a72a2cc40 has
failed.
If this error persists you could try removing the cache directory
'/home/travis/.rvm/gems/ruby-2.1.3/cache/bundler/git/exlibris-aleph-8c158a3cae6b9151bfb0cea18a61997a27b64ff5'
The command "eval bundle install --without development" failed. Retrying, 3 of 3.
Fetching source index from https://rubygems.org/
Updating git://github.com/barnabyalter/exlibris-aleph.git
fatal: Could not parse object '216a72a2cc40d6b0263e4963ae77138c6fd536e9'.
Git error: command `git reset --hard 216a72a2cc40d6b0263e4963ae77138c6fd536e9`
in directory
/home/travis/.rvm/gems/ruby-2.1.3/bundler/gems/exlibris-aleph-216a72a2cc40 has
failed.
If this error persists you could try removing the cache directory
'/home/travis/.rvm/gems/ruby-2.1.3/cache/bundler/git/exlibris-aleph-8c158a3cae6b9151bfb0cea18a61997a27b64ff5'
The command "eval bundle install --without development" failed 3 times.
The command "bundle install --without development" failed and exited with 11 during .`

**Comment by da70** [comment]
I have to leave soon for an appointment, but I checked real quick to see if the commit that Travis can't find is in the referenced repo or not, and it appears to be missing:

```
david@GURGI:dlts/> git clone git://github.com/barnabyalter/exlibris-aleph.git
Cloning into 'exlibris-aleph'...
remote: Counting objects: 789, done.
remote: Total 789 (delta 0), reused 0 (delta 0), pack-reused 789
Receiving objects: 100% (789/789), 315.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (327/327), done.
Checking connectivity... done.
david@GURGI:dlts/> cd exlibris-aleph/
david@GURGI:exlibris-aleph/> git log 216a72a2cc40d6b0263e4963ae77138c6fd536e9
fatal: bad object 216a72a2cc40d6b0263e4963ae77138c6fd536e9
david@GURGI:exlibris-aleph/> git show 216a72a2cc40d6b0263e4963ae77138c6fd536e9
fatal: bad object 216a72a2cc40d6b0263e4963ae77138c6fd536e9
david@GURGI:exlibris-aleph/> 
```

**Comment by eshadatta** [comment]
@NYULibraries/dlts , 
I emailed Barnaby and he mentioned that "barnabyalter/exlibris-aleph is only to work with older versions of Rails". Basically, the old login gems are no longer supported, which means that the new login strategy needs to be implemented.

**Comment by barnabyalter** [comment]
@eshadatta correction: exlibris-aleph has nothing to do with login. it is just an api into aleph. my fork was setup to work with Ichabod specifically because it had older gems. you can just point that to the rubygems version of exlibris-aleph and this should work as expected. i did it locally and all tests passed. 

the login gems should be updated though. they continue to work but they aren't getting any new updates. that can be addressed separately.

**Comment by eshadatta** [comment]
@barnabyalter ,

ok, cool, thanks. Yeah, we will have that as a chore. I'll go ahead and use the stopgap method you mentioned. Thanks.

**Pull request closed without merging**
