### PR TITLE
Chore/metadata fields

### PR DESCRIPTION
**Pull request by eshadatta**
@NYULibraries/hydra ,
I've added the yml file functionality to the code and added rspec tests. I added a module to app/model/concerns. Please let me know if you have a problem with this approach. I DRY'd up the code in model/nyucore.rb and in lib/resource.rb. There is a hack in the model/nyucore.rb to keep the tests passing. I don't think we need separate arrays for Nyucore and the "extra" singles and multiples. We're not really doing anything with them. I haven't changed that since I wanted to bring up the discussion within the ichabod team. There were some extra fields that weren't there before this work, so I added them to the factory. Please review and let me know if you have questions. Thanks.

### CODE REVIEW

**Comment by da70** [comment]
According to [Github comparison of `development` and `chore/metadata fields`](https://github.com/NYULibraries/ichabod/compare/development...chore/metadata_fields), `chore/metadata fields` can be automatically merged without rebasing.  However, this branch may or may not be considered stale depending on whether we define staleness to be being behind `development` branch or not merge-able into `development` without conflict.

The [Github network graph](https://github.com/NYULibraries/ichabod/network) shows that `chore/metadata fields` is missing commits from `development`, namely the commits that were merged from [#211](https://github.com/NYULibraries/ichabod/pull/211) and [#212](https://github.com/NYULibraries/ichabod/pull/212).  `chore/metadata fields` [commit history for `chore/metadata fields`](https://github.com/NYULibraries/ichabod/commits/chore/metadata_fields) shows this as well.  `git` itself clearly indicates a difference in the files in question:

```Shell
david@GURGI:ichabod/> date
Thu Feb 18 11:40:09 EST 2016
david@GURGI:ichabod/> git fetch origin development
From github.com:NYULibraries/ichabod
 * branch            development -> FETCH_HEAD
david@GURGI:ichabod/> git fetch origin chore/metadata_fields
From github.com:NYULibraries/ichabod
 * branch            chore/metadata_fields -> FETCH_HEAD
david@GURGI:ichabod/> git diff development chore/metadata_fields -- README.md
diff --git a/README.md b/README.md
index 7979555..640ebc3 100644
--- a/README.md
+++ b/README.md
@@ -22,24 +22,14 @@ Students, faculty, researchers - can search through collection metadata and get
 ## Sample Data Ingest
 
 Rake tasks available to ingest data from "ingest" directory.
-```
-    rake ichabod:load['nyu_press_open_access_book','http://discovery.dlib.nyu.edu:8080/solr3_discovery/nyupress/select']
-    # Load first five records only (start = 0, rows = 5)
-    rake ichabod:load['nyu_press_open_access_book','http://discovery.dlib.nyu.edu:8080/solr3_discovery/nyupress/select','0','5']
-```
-```
-    rake ichabod:load['faculty_digital_archive_ngo','https://archive.nyu.edu/request','hdl_2451_33605']
-    # Load five records only (rows = 5)
-    rake ichabod:load['faculty_digital_archive_ngo','https://archive.nyu.edu/request','hdl_2451_33605','5']
-```
-```
+
     rake ichabod:load['spatial_data_repository','./ingest/sdr.xml']
-```
+    rake ichabod:load['faculty_digital_archive','./ingest/stern.xml']
+
 ... and to purge data based on same data files.
 
-    rake ichabod:delete['nyu_press_open_access_book','http://discovery.dlib.nyu.edu:8080/solr3_discovery/nyupress/select']
-    rake ichabod:delete['faculty_digital_archive_ngo','https://archive.nyu.edu/request','hdl_2451_33605']
     rake ichabod:delete['spatial_data_repository','./ingest/sdr.xml']
+    rake ichabod:delete['faculty_digital_archive','./ingest/stern.xml']
 
 ## Resources
 
david@GURGI:ichabod/> git diff development chore/metadata_fields -- lib/ichabod/resource_set/source_readers/oai_dc_http_reader.rb
diff --git a/lib/ichabod/resource_set/source_readers/oai_dc_http_reader.rb b/lib/ichabod/resource_set/source_readers/oai_dc_http_reader.rb
index ac653df..9a9776a 100644
--- a/lib/ichabod/resource_set/source_readers/oai_dc_http_reader.rb
+++ b/lib/ichabod/resource_set/source_readers/oai_dc_http_reader.rb
@@ -39,7 +39,7 @@ module Ichabod
         def records
          @records=[]
          unless load_number_of_records.nil?
-           response_oai.first(load_number_of_records.to_i).each { |oai_record| @records << oai_record.metadata }
+           response_oai.first(load_number_of_records).each { |oai_record| @records << oai_record.metadata }
          else
            response_oai.each { |oai_record| @records << oai_record.metadata }
          end
david@GURGI:ichabod/> 
```

And yet neither the [pull request "Files changed" view](https://github.com/NYULibraries/ichabod/pull/213/files) nor the [branch comparison "Files changed" view (`development` vs `chore/metadata_fields`)](https://github.com/NYULibraries/ichabod/compare/development...chore/metadata_fields) list these files or their changes at all.

Interestingly, if you reverse the direction of the Github comparison to [(`chore/metadata_fields` vs `development`)](https://github.com/NYULibraries/ichabod/compare/chore/metadata_fields...development), you get the changes from PR#211 and PR#212 but not Esha's changes on the `chore/metadata_fields` branch.

I did branch compares in straight `git` and they are different than github's.  See attached.  They each have diffs for 11 files, which would appear to be the correct total (rather than Github's 9 and 2 files).  On first glance they also appear to be symmetrical changes.  I've attached output of each.

All that said, I did a test merge on my workstation and it went through.  For `README.md` and `oai_dc_http_reader.rb`, the `development` branch was favored.  Could be Github's version of `git` will do the same, and that's why they are calling this an automatic merge.  I thought this was worth recording though because I was surprised by these discrepancies.

Whether or not this branch needs to be rebased depends on what we want our protocol to be.  I personally think we should always rebase if behind `development` just to keep things consistent and easy, and also because sometimes it's cleaner to resolve bugs - as opposed to merge conflicts, which are not present here - on the topic branch rather than the integration branch.
If we don't rebase first and the merge introduces bugs, in theory the tests would catch them on the merge and Travis or Github would rollback.  At the same time sometimes things slip past the test suite whereas they wouldn't escape a developer who was rebasing their branch and doing sanity checks on their own.

**Comment by eshadatta** [comment]
@da70 , @NYULibraries/hydra 

I think we should rebase this against development so that this branch reflects the most current state of development. I just forgot to do it.  Usually the workflow has been,  push up our latest changes, get feedback, rebase against dev, push up again to get final approval. Apologies for not rebasing earlier.

**Comment by da70** [comment]
@eshadatta No need for apologies at all.  I think normally people wait for Travis or Github to tell them that the branch is stale, and they didn't say anything this time.  That's why I wrote up what I observed because I was surprised by that, although I can understand the possible rationale.  I found out the branch was behind on commits purely by accident, because I was trying to load the first 5 rows `faculty_digital_archive_ngo` and the `rake` task failed.
I was also really puzzled as to why Github's compare branch function is completely different from `git`'s on my computer and wanted to share that in case others encounter weirdness.

**Comment by da70** [comment]
@eshadatta  Below are some notes on what I've looked at so far.  If I have time I can try and look at the rest.  Also, if these are changes you agree with, I'd be totally happy to do it as part of the user story Corey and I are pair-programming together ([#113569497](https://www.pivotaltracker.com/n/projects/1025368/stories/113569497)).
You've already done all the heavy lifting!  Much appreciated.

## As ActiveSupport::Concern

I didn't really know what these were so read about them a little.  They appear to be for reusing code amongst models.  Do we need this to be in more than one model?  At the moment it's used in `Nyucore` model, but also `Ichabod::ResourceSet::Resource`.  That being the case I wonder if we should just put the module in `lib/`, or else create a singleton object (an object for which the application only ever makes one instance) in the initializer called METADATA_FIELDS which in addition to the data from the YAML file would also containt the methods from the module.

## Naming: md -> metadata

Could we change:

* `md_fields.rb` -> `metadata_fields.rb`
* `module MdFields` -> `module MetadataFields`
* `get_md_fields.rb` -> `get_metadata_fields.rb`
* `MD_FIELDS` -> `METADATA_FIELDS`

Just for clarity and readability and also to keep consistent with YAML file name `metadata_fields.yml`?

## Module `md_fields.rb`

* Would suggest splitting `DEFAULT_VALUE = 'all'` into something like this:

```Ruby
NAMESPACE_ALL = 'all'
MULTIPLE_ALL  = 'all'

DEFAULT_NAMESPACE = NAMESPACE_ALL
DEFAULT_MULTIPLE  = MULTIPLE_ALL
```

This makes both param defaults individually configurable and also separates the options of "give me everything" and "give me whatever your default is, I don't care".  This could prevent bugs later if the default is changed from 'all' to something else for one or the other param.  (See below)

* Since `process_source_fields` and `parse_all_fields` basically do the same thing, might want to settle on just "parse" or "process" for both, or a different verb maybe.  Since this method mutates one of its arguments, it might be good to indicate that in the name (similarly to the Ruby convention of adding "!" to methods that mutate the object they are called on).  So maybe something like `add_all_fields( fields, multiple )` and `add_fields_for_namespace( fields, multiple, namespace )` - keeping the parameters list as parallel as possible for least surprise.  I think maybe it would be better to not use the word "source" in the method because that is Ichabod-specific, and we might want to re-use this elsewhere, or we might not use that "source" distinction forever.

* A suggested rewrite of this:

```Ruby
      if MD_FIELDS.has_key?(chk_key)
          process_source_fields(chk_key,multiple,fields)
      elsif ns == DEFAULT_VALUE 
          parse_all_fields(multiple,fields)
      end
```

...would be this:


```Ruby
      # Note we can't use `ns == DEFAULT_NAMESPACE` (or in original code, `ns == DEFAULT_VALUE`)
      # because there may come a time when DEFAULT_NAMESPACE (or DEFAULT_VALUE) are changed to
      # to something else besides 'all'.  The default could become 'nyucore', for example.
      if ns == NAMESPACE_ALL
          add_all_fields(fields, multiple)
      elsif METADATA_FIELDS.has_key?(chk_key)
          add_fields_for_namespace(fields, multiple, namespace)
      else
          # User has specified a namespace that is valid, but not present in the YAML file.
          # Either do nothing or raise an error or warning.
      end
```

* Suggested re-format, rewrite:

```Ruby
   output = multiple == DEFAULT_VALUE ? true : MD_FIELDS[ns][field][:multiple] == multiple
```

...to...

```Ruby
   output = ( multiple == NAMESPACE_ALL ) ?
                true :
                METADATA_FIELDS[ns][field][:multiple] == multiple
```

...just for readability.

**Comment by da70** [comment]
##`md_fields_spec.rg`

```Ruby
  	    context 'use of process_md_fields in an instance of a class' do
  	       subject { dummy_class.new }
  	       it { subject.should be_an_instance_of(dummy_class) }
  	       it { should respond_to(:process_md_fields) }
  	    end
```

* Typo: "in an instance of a class" -> "is an instance of a class"
* This assertion:
```Ruby
  	       subject { dummy_class.new }
  	       it { subject.should be_an_instance_of(dummy_class) }
```
...may not be necessary.  If I understand it correctly, the only way it can fail is if Ruby itself had a bug, or else if RSpec `subject` had a bug.
* Maybe it would be good to test the metadata fields in some additional ways:
** Number of namespaces and possibly their values
** Number of fields: total and/or per namespace, and possibly some or all of the values
** Structure of the fields: each field should have the required attributes.

Again, this is something Corey can do in the branch we've made off of yours if you need a break from this.

**Pull request closed without merging**
