### PR TITLE
Feature/research guide facet

### PR DESCRIPTION
**Pull request by chrpr**
@jgpawletko @NYULibraries/hydra 

Apologies for the premature trigger pull before. This replaces PR #137 for story https://www.pivotaltracker.com/story/show/91605284

Added a 3 rspecs and a cuke and tweaked the collections and resource set to get everything passing. Requires a reload of lib_guides resource_set to deploy to dev for project owner review.

Then had to delete and rebase to pick up new local mustache-rails repo.

Let me know if you need anything further from me on this one.

Thanks,
-Corey

### CODE REVIEW

**Comment by jgpawletko** [comment]
@chrpr FYI: I restarted the Travis builds as they were failing...

**Comment by jgpawletko** [comment]
@chrpr 
One minor comment:
You should be able to DRY [this](https://github.com/NYULibraries/ichabod/blob/feature/research_guide_facet/spec/ichabod/resource_set/source_readers/lib_guides_xml_file_reader_spec.rb#L10-L11) up a little.
```
          allow(resource_set).to receive_messages(
            filename:  lib_guides_xml_filename,
            collection_code:  collection_code)
```
Thanks!

**Comment by chrpr** [comment]
Thanks @jgpawletko 

I incorporated your suggestion. There's a bunch of other source_reader specs that have the same pattern (voice, masses, press, rosie, oai_dc). Would you like me to go through and similarly DRY up for consistency's sake? 

Also, not sure what to do about the failing travis jobs. I'll keep an eye on them and restart if I notice red. Keep me posted in #140.

**Comment by chrpr** [comment]
WHoops. @jgpawletko actually that change blew up the rspecs. Will try to figure out how to implement your suggestion and get back to you here.

**Comment by jgpawletko** [comment]
>   Hi Corey,
Don't worry about DRYing up the code then.
I'll look into the pattern, and will DRY things up if I can.
Best-
Joe
On Monday, June 1, 2015, chrpr <notifications@github.com> wrote:

> WHoops. @jgpawletko <https://github.com/jgpawletko> actually that change
> blew up the rspecs. Will try to figure out how to implement your suggestion
> and get back to you here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/138#issuecomment-107746363>.
>


-- 
Sent from a mobile device, please excuse brevity, typos

**Comment by chrpr** [comment]
@jgpawletko I'm going to keep having a look at it. The method is coming up undefined, but it doesn't seem like that should be the case.

**Comment by jgpawletko** [comment]
That suggestion came from rspec-mock, but I just looked through the Gemfile
and I don't see rspec-mock in there.

Apologies.

**Comment by chrpr** [comment]
@jgpawletko It's in the Gemfile.lock:
https://github.com/NYULibraries/ichabod/blob/development/Gemfile.lock#L442

2x: 
https://github.com/NYULibraries/ichabod/blob/development/Gemfile.lock#L450

**Comment by ekate** [comment]
just in case -there might be problems with builds as servers for
collections are down

On Mon, Jun 1, 2015 at 7:57 PM, Joseph Pawletko <notifications@github.com>
wrote:

> That suggestion came from rspec-mock, but I just looked through the Gemfile
> and I don't see rspec-mock in there.
>
> Apologies.
>
> On Mon, Jun 1, 2015 at 7:45 PM, chrpr <notifications@github.com> wrote:
>
> > @jgpawletko <https://github.com/jgpawletko> I'm going to keep having a
> > look at it. The method is coming up undefined, but it doesn't seem like
> > that should be the case.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/NYULibraries/ichabod/pull/138#issuecomment-107748174
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/138#issuecomment-107749435>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by chrpr** [comment]
@jgpawletko I rolled back to the previous, though now cucumber won't run and getting errors on authorize edit button rspecs, probably due to maintenance @ekate mentioned.

I will rerun rspecs and cukes locally, and restart travis jobs either later tonight or first thing in the morning.

**Comment by ekate** [comment]
Hi Corey,
errors in cucs might be due to the stopped dlts servers. The servers  are
back now. Try again

Kate

On Mon, Jun 1, 2015 at 8:27 PM, chrpr <notifications@github.com> wrote:

> @jgpawletko <https://github.com/jgpawletko> I rolled back to the
> previous, though now cucumber won't run and getting errors on authorize
> edit button rspecs, probably due to maintenance @ekate
> <https://github.com/ekate> mentioned.
>
> I will rerun rspecs and cukes locally, and restart travis jobs either
> later tonight or first thing in the morning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/138#issuecomment-107752555>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by chrpr** [comment]
@ekate @jgpawletko All the rspecs and cukes that were failing for me locally are passing now. It doesn't look like I have permission to restart the travisci builds, but I think those failures are unrelated to the downtime. Will follow up Wed morning if I don't have time tomorrow.

**Pull request closed without merging**
