### PR TITLE
Feature/iso language code map

### PR DESCRIPTION
**Pull request by eshadatta**
Rebasing code again after it was out-of-date with the Masses code. Referencing #114 which was the old PR. @jgpawletko @NYULibraries/hydra, if someone could review this PR, I'd appreciate it.

*Edited to correct the name of the collection. A similar name was on my brain*

### CODE REVIEW

**Comment by eshadatta** [comment]
Ok @NYULibraries/hydra , I rebased the code, I ran cucumber tests on my machine. After loading the Masses on my local machine, it ran. Does this need a vcr to run because it's failing the cucumber test on Travis? This is getting frustrating.

**Comment by eshadatta** [comment]
Apologies for the spam. It ran without errors. I guess I was looking at an open old PR.

**Comment by jgpawletko** [comment]
Hi @eshadatta 

You may want to take advantage of a case statement [here](https://github.com/NYULibraries/ichabod/blob/feature/iso_language_code_map/lib/ichabod/resource_set/resource.rb#L62-L66), e.g., 
```ruby
language = case
           when value.is_a?(Array)  then value
           when value.is_a?(String) then [value]
           else raise ArgumentError.new("Expecting #{value} to be an Array or String")
           end
```

A couple of questions about the code [here](https://github.com/NYULibraries/ichabod/blob/feature/iso_language_code_map/lib/ichabod/resource_set/resource.rb#L69-L92):
* According to the documentation, `ISO_639.search` [always returns an `Array`](http://www.rubydoc.info/gems/iso-639/0.2.5).  Therefore, you should iterate over the result instead of using a `while` loop, which is consistent with the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#syntax).
* As written, [this code](https://github.com/NYULibraries/ichabod/blob/feature/iso_language_code_map/lib/ichabod/resource_set/resource.rb#L78-L88) looks like it loops over all elements of the `Array` returned by the `ISO_639.search`, but returns a scalar value: the string stored in `iso_lang_code`, which gets overwritten on each match.  Can you terminate the loop on the first match?  If not, does a scalar value capture all of the information you need?
* [this](http://matthewcarriere.com/2008/06/23/using-select-reject-collect-inject-and-detect/) shows some other powerful ways to iterate over collections of objects, and may inform the way you process the `ISO_639.search` results.

**Comment by eshadatta** [comment]
@jgpawletko ,

Thanks very much for your comments. ISO_639.search returns an array of arrays. I changed the iteration to be more consistent with ruby style by switching to each_index/each to iterate within the arrays. Also, now I am terminating the loop on first match. This was very helpful, thanks. I've pushed up the changes. Please let me know if there's any other feedback.

Thanks.

**Comment by jgpawletko** [comment]
Hi @eshadatta ,
I'll merge this after Travis passes...
Thanks!
Joe

**Comment by eshadatta** [comment]
@jgpawletko Thanks for showing me how to restart a Travis job. It passed. Thanks.

**Pull request merged**
