### PR TITLE
Chore/change value book

### PR DESCRIPTION
**Pull request by eshadatta**
Rebased to add new gem path and version. Referencing PR #132.

### CODE REVIEW

**Comment by jgpawletko** [comment]
@eshadatta 
Thanks for making the change suggested in #132 .
Feel free to merge this PR once Travis and Jenkins are green.

**Comment by eshadatta** [comment]
@jgpawletko Only one job is refusing to pass because of connectivity issues, the rest have passed. Shall I merge? Thanks.

**Comment by jgpawletko** [comment]
@eshadatta 
please wait until green.
I took the liberty of restarting the failed job.
Thanks!

**Comment by eshadatta** [comment]
@jgpawletko it failed again and I just restarted it again.

**Comment by jgpawletko** [comment]
@eshadatta 
ugh.
I thought more about this. I think it's OK to merge because all of the configurations in the `travis-ci/pr` build passed.
thanks!

**Pull request merged**
