### PR TITLE
Feature/add isbn

### PR DESCRIPTION
**Pull request by eshadatta**
Referencing PR #134.  Fixed Rosie vcr to read from dev json endpoint. One change I noticed was that the Rosie identifier has changed from this: 4jeads-node-827 to ROSIE_INTERVIEW_001. If I look at the solr endpoint which doesn't have all of the fields parsed out, I get this: 4jeads-node-827 but if I used the json endpoint, I get this: ROSIE_INTERVIEW_001. I am using the json endpoint, so all the identifiers will be ROSIE_INTERVIEW_{number}. I am planning on re-indexing the Rosie content, so that there will be no duplicate records with different identifiers. Please let me know if there are any problems with this or if there is any feedback. Thanks.

### CODE REVIEW

**Comment by eshadatta** [comment]
@jgpawletko @NYULibraries/hydra ,

General question about cuke tests for Masses. Should we vcr it since the cuke tests on travis regularly trip on it and we have to restart jobs for it? I have to restart and almost every time it's because it didn't connect for whatever reason. Thanks.

**Comment by jgpawletko** [comment]
@eshadatta  

Thank you for your comment.  It's not just "The Masses". Corey's builds are failing because of "Lib Guides". 
 
I'm working on a tweak to the Capybara config in the Travis environment that, I hope, will resolve the `Capybara:ElementNotFound` errors.  I want to test it out first.

If it resolves the issues, I will create a hotfix branch on development that everyone can merge back into their branches.

**Comment by eshadatta** [comment]
ok, thanks!

**Comment by eshadatta** [comment]
@jgpawletko This PR is ready for review. Everything passes. I had questions about Rosie identifiers which I've put at the top of the PR. These questions may also be for @dlovins @ckassel or anyone else @NYULibraries/hydra. Basically, I'm concerned that I will be duplicating records with different identifiers. To get the same identifiers as last records, I would have to also call the solr records and grab the identifiers for that. If that's the route, I should go, please let me know, and I can go ahead and do that. Otherwise the record ids are different. We would need to delete and re-load Rosie for dev and prod. Please let me know your recommendations on going forward. Thanks.

**Comment by eshadatta** [comment]
Hi @NYULibraries/hydra @jgpawletko 

I know we briefly talked about this at the sprint planning. But please give me the official OK so that it's documented here about deleting and reloading the rosie data with new identifiers and if this PR could be reviewed(the actual work was about adding an isbn field but then I also had to change the Rosie loader to read from a json endpoint), I would appreciate it. Thanks!

**Comment by jgpawletko** [comment]
@eshadatta please proceed as we discussed in the sprint planning meeting: delete and reload the Rosie collection data, which will result in new identifiers for the Rosie items.

**Pull request merged**
