### PR TITLE
Feature/add wojnarowicz - (need feedback)

### PR DESCRIPTION
**Pull request by eshadatta**
@jgpawletko , @NYULibraries/hydra ,

This pull request finishes the David Wojnarowicz [story](https://www.pivotaltracker.com/n/projects/1025368/stories/99084376) in pivotal tracker.  I have  questions about this.

1. I couldn't send proper url parameters to the finding aids bridge [portal](https://specialcollections.library.nyu.edu/search). It wasn't encoding it correctly. So, I have a rather ugly hack [here](https://github.com/NYULibraries/ichabod/compare/feature/add_wojnarowicz?expand=1#diff-91efdd0940d8aedd7c2e88b98671026eR9). If I tried to send it through the params argument using Faraday, it never encoded it the way the portal could translate it. It would be f = arg1 & f = arg2 rather than the way I have put it in that file.
2. I've put in constants in the [fab reader](https://github.com/NYULibraries/ichabod/compare/feature/add_wojnarowicz?expand=1#diff-44ab4052d2a371cb4090731c746dba90R12) instead of passing it through the model since any other collection using the fabreader would be using the same values. I thought of putting these in configula and referencing them as ENV variables instead of putting them deep in the reader but then it would fail in travis. Please let me know if you have any thoughts on this.

EDIT: Adding to say that for point 1, this could change later once we talk to Barnaby about how to tweak the FAB to have it also work as an api. But it's an ugly hack for now.

Please let me know if you have any other feedback as well. Thanks.

### CODE REVIEW

**Comment by da70** [comment]
Thoughts on #2:

Setting aside for the moment whether we should put this info in the reader class or in a configuration file/area, one thing to note is that in Ruby, constants are not really constant.  Any variable name that starts with an uppercase letter is automatically considered a Ruby constant, which dismayingly can actually be changed as easily as any other non-constant variable:

```
david@GURGI:ichabod/> irb
2.1.3 :001 > URL="http://constant.com"
 => "http://constant.com" 
2.1.3 :002 > URL="This can be changed anytime, anywhere"
(irb):2: warning: already initialized constant URL
(irb):1: warning: previous definition of URL was here
 => "This can be changed anytime, anywhere" 
2.1.3 :003 > puts URL
This can be changed anytime, anywhere
 => nil 
```

Making a variable a constant in Ruby just means you'll get warnings when you change it (as in above).  The change will still happen.

Esha and I talked a little bit after the scrum, and she had thought about making this a read-only attribute, but before going through that trouble she wanted feedback from the group about this configuration in general.  If we do decide to keep this config in `fab_reader.rb`, I recommend making these strings read-only attributes to guarantee immutability.

Since we were talking about configuration, we also recalled our group discussion from last month about refactoring to remove the duplication in configuration, as it is extra work to have to change the same info in multiple places, and also increases the changes for bugs.  Maybe we can set up a chore for refactoring our duplicate configuration into a simple, plain-old Ruby module?

**Comment by da70** [comment]
Feedback on item #1:

Here is a test script showing a couple methods for constructing the query using Faraday params:

```ruby
require 'faraday'

catalog_url = 'https://specialcollections.library.nyu.edu/search/catalog.json'

# Get expected JSON
hardcoded_query = '?f%5Bcollection_sim%5D%5B%5D=David+Wojnarowicz+Papers&f%5Bdao_sim%5D%5B%5D=Online+Access&f%5Bformat_sim%5D%5B%5D=Archival+Object'
expected_response = Faraday.new( :url => catalog_url + hardcoded_query).get.body

# The params:
# f[collection_sim][]=David Wojnarowicz Papers
# f[dao_sim][]=Online Access
# f[format_sim][]=Archival Object

puts "\n\n####### METHOD 1 #######\n\n"

conn = Faraday.new(
    :url => catalog_url,
) do |faraday|

  faraday.response :logger
  faraday.adapter   Faraday.default_adapter
  faraday.options.params_encoder = Faraday::FlatParamsEncoder
end

response = conn.get do |request|
  collection_sim = '[collection_sim][]'
  dao_sim = '[dao_sim][]'
  format_sim = '[format_sim][]'

  request.params["f#{collection_sim}"] = 'David Wojnarowicz Papers'
  request.params["f#{dao_sim}"       ] = 'Online Access'
  request.params["f#{format_sim}"    ] = 'Archival Object'
end

params1_response = response.body

if (params1_response == expected_response) then
  results = "Using Faraday params method 1: OK\n"
else
  results = "Using Faraday params method 1: FAIL\n"
end

puts "\n\n####### METHOD 2 #######\n\n"

response = conn.get catalog_url, {
    :'[f][collection_sim][]'.to_sym => 'David Wojnarowicz Papers',
    :'[f][dao_sim][]'.to_sym        => 'Online Access',
    :'[f][format_sim][]'.to_sym     => 'Archival Object',
}

params2_response = response.body

if (params2_response == expected_response) then
  results += "Using Faraday params method 2: OK\n"
else
  results += "Using Faraday params method 2: FAIL\n"
end

puts "\n\n=======TEST RESULTS=======\n\n"

puts results
```

There are probably other ways.  The other possibility is use a generic url-encoding utility that is not Faraday to build the query string and then concatenate that query string to Faraday more or less as you are already doing.

Hope this helps.

**Comment by jgpawletko** [comment]
@eshadatta 
@da70 :+1: for `METHOD #1` and :+1: for your detailed comment!

**Comment by eshadatta** [comment]
@da70 , awesomesauce! Thanks! @jgpawletko, thanks for continuing to look into this.

**Comment by jgpawletko** [comment]
Hi @eshadatta, 
do you have enough to go on, or do you need more feedback?

**Comment by eshadatta** [comment]
@jgpawletko ,

I have enough to deal with the url encoding issue. Did you have any thoughts on the second point? Otherwise, I can put them in a yaml file and that will remove the issue of having to define a common variable deep in a class. If everything else is good, I will go ahead and address the issues mentioned here.

Thanks!

**Comment by jgpawletko** [comment]
@eshadatta yaml file sounds good to me.

**Pull request closed without merging**
