### PR TITLE
Chore/about page

### PR DESCRIPTION
**Pull request by eshadatta**
Created an about page, per this pivotal tracker [chore]( https://www.pivotaltracker.com/n/projects/1025368).  I created an about route which points to the same action as the catalog index. In that, I created a conditional statement to render an about partial depending on the route being called. I couldn't figure out another seamless way to do it since the facets and the user link partial still needed to be rendered and I didn't want to edit the catalog controller. Please let me know if there is a better way.

Thanks.

### CODE REVIEW

**Comment by eshadatta** [comment]
@NYULibraries/hydra ,

Hi, this is a simple chore. But I would appreciate feedback if what I did was fine or if there's a better way? I thought about creating a static pages controller and view but thought it was overkill for this. I thought we could always iterate to that, if more static pages are needed. Also, I thought about using a yml for the collections listed with their associated urls. Again, I invoked the agile hashtag...let's iterate on it. Unless you guys think it's best to do it now. Let me know. Thanks.

**Comment by chrpr** [comment]
@eshadatta I agree that iteration is the way to go here, but we probably want to add a chore to update this to the yaml approach when/if we start adding collections at a faster pace.

I think the more fancy approach down the road is to use the help view model used in finding aids and elsewhere:
https://github.com/NYULibraries/findingaids/tree/development/app/views/help

This drives the right-hand sidebar of special collections search:
https://specialcollections.library.nyu.edu/search

When we're ready to have more tooltips like this, we can move the FAQ to this kind of pop-over as well.

**Comment by eshadatta** [comment]
@chrpr ,

Great, thanks for the comments. Yes, the finding aids approach is nice, I had totally forgotten about that. It would be nice to implement a similar approach if this becomes more public facing and we have more to say. I'll go ahead and merge this. Thanks.

**Comment by dlovins** [comment]
@chrpr (and @eshadatta) thanks pointing out the Special Collections Search approach (using the help view model). Nice choice for future iterations.

**Pull request merged**
