### PR TITLE
Chore/retool resource delete code

### PR DESCRIPTION
**Pull request by eshadatta**
Hi,

I updated the delete code to delete by dataset prefix. The tests in spec/ichabod/resource_sets/base_spec.rb are weirdly inconsistent in lines 207 and 215. They seem to only pass if I keep the commented out code(and not delete the commented out code). Anyways,I'm seeing if the tests pass here and if that's the case, I'll delete it. I don't know if there's some environment hiccup that preventing the tests to run successfully. Thanks

### CODE REVIEW

**Comment by eshadatta** [comment]
@NYULibraries/hydra @jgpawletko 
Hi,

So, I have done this chore to delete the dataset by its prefix. The code runs fine but two rspec tests are inconsistently failing and I can't figure out why. In travis-ci/push build, jobs 824.1 and 824.2 fail(with 1 test and both tests failing respectively for that build). However, 824.3 passes. In travis-ci/pr  build, all jobs fail. 825.1 fails with 1 test and 825.2 and 825.3 fail for both tests. This happens locally too. It sometimes passes and sometimes fails on one test and occasionally fails on both. I can't figure out why this is happening. If one of you has an approach that I could use or has some insight into this, I'd really appreciate it. 

Thanks.

**Comment by jgpawletko** [comment]
@eshadatta 
looking now...

**Comment by jgpawletko** [comment]
Hi @eshadatta ,
A quick update: I definitely see interaction between the tests.
I've noted two different seeds, one that passes, and one that fails:
```
failing seed: $ rspec ./spec/ichabod/resource_set/base_spec.rb --seed 12449
passing seed: $ rspec ./spec/ichabod/resource_set/base_spec.rb --seed 4333
```
I'll keep digging and will let you know what I find.
best-
joe

**Comment by eshadatta** [comment]
@jgpawletko , cool, thanks so much for digging into this

**Comment by eshadatta** [comment]
Documenting process to debug failures. Checking test order with passing and failing rspec seeds.
```
1165 examples, 0 failures, 5 pending

Randomized with seed 44844

This is a passing seed.
Get the seed information:
rspec --seed 44844 -f json > ~/ichabod_passing.json

Parse json file to get information. Used a ruby script:
require 'json'
data = JSON.parse(File.read('ichabod_passing.json'))
examples = data['examples'].map do |example|
  puts "#{example['file_path']}:#{example['line_number']}:#{example['full_description']}"
end

**Comment by jgpawletko** [comment]
Hi @eshadatta,
A few questions:
* could you add an example (spec) for [`get_records_by_prefix`](https://github.com/NYULibraries/ichabod/blob/chore/retool_resource_delete_code/lib/ichabod/resource_set/base.rb#L151-L157) ?
* if `get_records_by_prefix` populates `@resources` as expected, then I think you should leave the rest of the `delete` method untouched.  Do you agree?
* I noticed in the updated base spec that there are some steps commented out and one example deleted.  Could you let me know why?
  * [here (commented out)](https://github.com/NYULibraries/ichabod/blob/chore/retool_resource_delete_code/spec/ichabod/resource_set/base_spec.rb#L205)
  * [here (commented out)](https://github.com/NYULibraries/ichabod/blob/chore/retool_resource_delete_code/spec/ichabod/resource_set/base_spec.rb#L216-217)
  * [here (deleted)](https://github.com/NYULibraries/ichabod/blob/development/spec/ichabod/resource_set/base_spec.rb#L265-L271)

Thanks!

**Comment by eshadatta** [comment]
Hi @jgpawletko ,

Thanks for looking at this. I commented [this](https://github.com/NYULibraries/ichabod/blob/chore/retool_resource_delete_code/spec/ichabod/resource_set/base_spec.rb#L205) and [this](https://github.com/NYULibraries/ichabod/blob/chore/retool_resource_delete_code/spec/ichabod/resource_set/base_spec.rb#L216-217) out just to see if they would do anything. When I was randomly commenting things out, it started to pass, so I wasn't sure what those actions were doing. I can restore them back. I deleted [this](https://github.com/NYULibraries/ichabod/blob/development/spec/ichabod/resource_set/base_spec.rb#L265-L271) because it's no longer an appropriate test for delete. I am not requiring the source reader to delete, only the class name, so it should not be tested. It would fail every time. I can add tests to see that a the class specified exists and that the prefix for that resource exists.

In terms of leaving the rest of the delete code intact, I'd like to. But here is the problem.
1. When I do the delete test by calling the ichabod rake task, I get a nyucore object because of how I'm getting the records.
2. When the rspec tests do the test, they do it through the resource. Originally, the delete task was getting an array of resource objects which were then converted to Nyucore object by the find...it was doing Nyucore.find and then it destroys the nyucore objects. My code bypasses getting an array of resources because it gets the Nyucore records directly. I need to change the rspec test(in dataloader_spec) to reflect that reality. But I was trying to get the base_spec tests to pass first before changing up another set of tests to get dataloader_spec to pass.

**Comment by eshadatta** [comment]
@jgpawletko ,

I added specs for `get_records_by_prefix`.  I changed the code slightly to test for prefix occurrence. The tests are still failing inconsistently but this time it seems to be only for editors: line 223. I deleted `before {base.delete}` because I'm actually not sure the purpose of that. Also, it's erroring out with the new delete test because it expects a prefix. The test is checking on the load functionality and I'm not sure the purpose about the "before" call for this. I can keep the before call and pass it a prefix, that's not a problem. Thanks again for your time on this.

**Comment by eshadatta** [comment]
@jgpawletko ,

I still get the inconsistent failing tests. This time two jobs passed all rspec tests, one of them failed in the cuke test for Masses. The other 2 jobs had failed rspec tests.

**Comment by ekate** [comment]
Hi,

I have the same problem with(sometimes) failing cucs for Masses. Probably
we should ask Alberto to look at it ?

Kate

On Tue, Jun 23, 2015 at 11:34 AM, eshadatta <notifications@github.com>
wrote:

> @jgpawletko <https://github.com/jgpawletko> ,
>
> I still get the inconsistent failing tests. This time two jobs passed all
> rspec tests, one of them failed in the cuke test for Masses. The other 2
> jobs had failed rspec tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/148#issuecomment-114547645>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
Yeah, I'm wondering if it's a connectivity thing for the Masses and a vcr might clear it up? I know @jgpawletko is investigating this.

**Comment by ekate** [comment]
I just talk to Alberto he also thinks it's a connection issue. It could
hardly be something else as I don't get that on jenkins and sometimes this
passes on travis too.

On Tue, Jun 23, 2015 at 2:34 PM, eshadatta <notifications@github.com> wrote:

> Yeah, I'm wondering if it's a connectivity thing for the Masses and a vcr
> might clear it up? I know @jgpawletko <https://github.com/jgpawletko> is
> investigating this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/148#issuecomment-114601902>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Pull request closed without merging**
