### PR TITLE
bug/stabilize test data

### PR DESCRIPTION
**Pull request by jgpawletko**
@NYULibraries/hydra 

**Overview:**
This PR improves the robustness of the test data by eliminating the reliance on the live ArchiveIt site, thus insulating builds from service outages and changes in the live data.

**Analysis:**
Some Ichabod scenarios for the _Archive It Archive of Contemporary Composers' Websites_ started
failing, even though the code related to those scenarios was unchanged.

The ArchiveItAccw scenarios relied on data taken from the [live site]( https://archive-it.org/collections/4049.json) and loaded during each build. 
    
The scenarios broke when the URL for a harvested site changed from `http://LouisKarchin.com`  to `http://www.louiskarchin.com`.
    
The harvested-site URL is used to generate the Ichabod identifier, so when the URL changed, 
the identifier specified in the scenarios was no longer present, thus the scenarios failed.
   
Similarly the `search.feature` expected `louiskarchin.com` and not `www.louiskarchin.com` so that scenario started failing as well.
    
The scenarios have been updated and the ArchiveItAccw test data are now loaded from a static file hosted on a DLTS server rather than being loaded from the live ArchiveIt site.

**Highlights**
* change `Ichabod::ResourceSets::ArchiveItAccw.initialize` to accept a `path` argument
* refactor `Ichabod::ResourceSets::SourceReaders::ArchiveItAccwReader` to use the new `path` method available in `ArchiveItAccw` resource set objects
* update scenarios and examples to reflect the new Louis Karchin URL: `www.louiskarchin.com`
* update `features/support/env.rb` to load ArchiveItAccw data from the DLTS host
* refresh the cassette used in ArchiveItAccw examples
* clean up some whitespace

### CODE REVIEW

**Comment by ekate** [comment]
Hi Joe,

Do I understand it correctly that we actually caught the problem with data
loader parameters by running this test ? I mean, if we had to run the data
loader not as the part of the test but as a regular job the error will be
the same ? Then probably it's good that test failed ? I understand that
when the site is off-line it's another case but still there is some value
in "live" testing...

Kate

On Wed, Feb 4, 2015 at 1:54 AM, Joseph Pawletko <notifications@github.com>
wrote:

> @NYULibraries/hydra <https://github.com/orgs/NYULibraries/teams/hydra>
>
> *Overview:*
> This PR improves the robustness of the test data by eliminating the
> reliance on the live ArchiveIt site, thus insulating builds from service
> outages and changes in the live data.
>
> *Analysis:*
> Some Ichabod scenarios for the *Archive It Archive of Contemporary
> Composers' Websites* started
> failing, even though the code related to those scenarios was unchanged.
>
> The ArchiveItAccw scenarios relied on data taken from the live site
> <https://archive-it.org/collections/4049.json> and loaded during each
> build.
>
> The scenarios broke when the URL for a harvested site changed from
> http://LouisKarchin.com to http://www.louiskarchin.com.
>
> The harvested-site URL is used to generate the Ichabod identifier, so when
> the URL changed,
> the identifier specified in the scenarios was no longer present, thus the
> scenarios failed.
>
> Similarly the search.feature expected louiskarchin.com and not
> www.louiskarchin.com so that scenario started failing as well.
>
> The scenarios have been updated and the ArchiveItAccw test data are now
> loaded from a static file hosted on a DLTS server rather than being loaded
> from the live ArchiveIt site.
>
> *Highlights*
>
>    - change Ichabod::ResourceSets::ArchiveItAccw.initialize to accept a
>    path argument
>    - refactor Ichabod::ResourceSets::SourceReaders::ArchiveItAccwReader
>    to use the new path method available in ArchiveItAccw resource set
>    objects
>    - update scenarios and examples to reflect the new Louis Karchin URL:
>    www.louiskarchin.com
>    - update features/support/env.rb to load ArchiveItAccw data from the
>    DLTS host
>    - refresh the cassette used in ArchiveItAccw examples
>    - clean up some whitespace
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/NYULibraries/ichabod/pull/128
> Commit Summary
>
>    - add ArchiveItAccw#path example
>    - add ArchiveItAccw#path
>    - add ArchiveItAccw default path
>    - update ArchiveItAccw source reader
>    - modify features/support/env.rb
>    - update ArchiveItAccw scenarios
>    - add ArchiveItAccw data
>    - refresh ArchiveItAccw cassette and examples
>
> File Changes
>
>    - *M* app/resource_sets/archive_it_accw.rb
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-0> (3)
>    - *M* features/edit_metadata_authorization.feature
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-1> (6)
>    - *M* features/search.feature
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-2> (2)
>    - *M* features/support/env.rb
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-3> (6)
>    - *M* lib/ichabod/resource_set/source_readers/archive_it_accw_reader.rb
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-4> (7)
>    - *A* spec/fixtures/4049.json
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-5> (1)
>    - *M*
>    spec/ichabod/resource_set/source_readers/archive_it_accw_reader_spec.rb
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-6> (12)
>    - *M* spec/resource_sets/archive_it_accw_spec.rb
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-7> (11)
>    - *M* spec/vcr_cassettes/resource_sets/archive_it_accw.yml
>    <https://github.com/NYULibraries/ichabod/pull/128/files#diff-8> (5586)
>
> Patch Links:
>
>    - https://github.com/NYULibraries/ichabod/pull/128.patch
>    - https://github.com/NYULibraries/ichabod/pull/128.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/128>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
This leads to another question about what happens if the data changes suddenly as in this case. Do we keep the "old" data? Should there be talk of versioning? What guarantee do we have of stability? I know these questions are also meant for the person who is curating this data and product owners.

**Comment by jgpawletko** [comment]
@ekate @eshadatta 

Hi Kate, 

Thank you for your comment.

The structure of the data provided via the ArchiveIt API hasn't changed, and the
data loader is working as it should.  The data loader didn't generate the error.

The tests started failing because the data **value** used in the RSpec examples and Cucumber features was changed on the live ArchiveIt site. The data loader did its job and loaded the new
(perfectly valid) value.

I agree that there is value is doing live data loading to ensure that the source data structure hasn't changed, but I believe that should be separate from testing whether or not the code works as it should
for a given structure.

As @eshadatta mentioned in her comment, and @chrpr has mentioned before, we may want to
start keeping a copy of the last harvested data.  I did add my snapshot data to the repo under `spec/fixtures`, but I think there is justification for saving a full set of data in case the API is no
longer supported.

Thanks-
Joe

**Comment by ekate** [comment]
Ah o.k. I got it now. You are right. There is still a question on how we
insure that our data is  up to date but it has nothing to do with testing

Kate

On Wed, Feb 4, 2015 at 1:01 PM, Joseph Pawletko <notifications@github.com>
wrote:

> @ekate <https://github.com/ekate> @eshadatta
> <https://github.com/eshadatta>
>
> Hi Kate,
>
> Thank you for your comment.
>
> The structure of the data provided via the ArchiveIt API hasn't changed,
> and the
> data loader is working as it should. The data loader didn't generate the
> error.
>
> The tests started failing because the data *value* used in the RSpec
> examples and Cucumber features was changed on the live ArchiveIt site. The
> data loader did its job and loaded the new
> (perfectly valid) value.
>
> I agree that there is value is doing live data loading to ensure that the
> source data structure hasn't changed, but I believe that should be separate
> from testing whether or not the code works as it should
> for a given structure.
>
> As @eshadatta <https://github.com/eshadatta> mentioned in her comment,
> and @chrpr <https://github.com/chrpr> has mentioned before, we may want to
> start keeping a copy of the last harvested data. I did add my snapshot
> data to the repo under spec/fixtures, but I think there is justification
> for saving a full set of data in case the API is no
> longer supported.
>
> Thanks-
> Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/128#issuecomment-72905023>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Pull request merged**
