### PR TITLE
Feature/csv file dataloader

### PR DESCRIPTION
**Pull request by ekate**

### CODE REVIEW

**Comment by jgpawletko** [comment]
Hi @ekate ,

Some comments:
* My understanding is that we are using different prefixes for each collection, therefore should [this](https://github.com/NYULibraries/ichabod/pull/149/files#diff-97a908684d04fc873c489c25ad8f06a3R2) be `faculty_digital_archive_service_data` or something shorter, e.g., `fda_service_data`, `fda_sd`? (I'm concerned with Fedora identifier length restrictions if you use the full name.)  With Esha's `delete by prefix` code, you won't be able to delete just this collection. 
  * (I just checked, it looks like the `fda` prefix is used for multiple collections already, e.g., FDA, FDA NGO..., so this might be a larger discussion point...)
* Is [this](https://github.com/NYULibraries/ichabod/pull/149/files#diff-fc5fbd791c89b73723c53d0f46c9a0a8R1) file used?  If not, could you delete it?
* some style comments:
  * [missing newline](https://github.com/bbatsov/ruby-style-guide#newline-eof) [here](https://github.com/NYULibraries/ichabod/pull/149/files#diff-d550dc0a4583f73aebd98ed220c5ed84R47)
  * suggest the following tweaks to [this section](https://github.com/NYULibraries/ichabod/blob/feature/csv_file_dataloader/app/resource_sets/faculty_digital_archive_service_data.rb#L22-L26), and [this section](https://github.com/NYULibraries/ichabod/blob/feature/csv_file_dataloader/spec/ichabod/resource_set/source_readers/csv_file_reader_spec.rb#L7-L9)
    * [line exceeds 80 chars](https://github.com/bbatsov/ruby-style-guide#80-character-limits) 
       see [here](https://github.com/bbatsov/ruby-style-guide#align-multiline-arrays) for how to address (the link refers to arrays, but idea still pertains to hashes).
    * [use ruby 1.9 Hash syntax when all keys are symbols](https://github.com/bbatsov/ruby-style-guide#hash-literals)

**Comment by ekate** [comment]
Hi Joe,

the file ingest/2451-33611.csv will be used by production ingest

**Comment by eshadatta** [comment]
@ekate ,

Hi Kate,

Just checking. Should I just rebase this against development? And re-submit the pull request? After that, is this ready to be merged to development?

**Comment by ekate** [comment]
I need to add some style changes. Will be done by end of the day tomorrow

On Mon, Jul 20, 2015 at 1:45 PM, eshadatta <notifications@github.com> wrote:

> @ekate <https://github.com/ekate> ,
>
> Hi Kate,
>
> Just checking. Should I just rebase this against development? And
> re-submit the pull request? After that, is this ready to be merged to
> development?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYULibraries/ichabod/pull/149#issuecomment-122965173>.
>



-- 
Ekaterina Pechekhonova
Digital Library Programmer/Analyst
New York University
Libraries
email: ekate@nyu.edu
phone: 212-992-9993

**Comment by eshadatta** [comment]
Great, thanks

**Pull request closed without merging**
