### PR TITLE
Chore/metadata fields

### PR DESCRIPTION
**Pull request by eshadatta**
Rebased branch. Referencing PR #213

### CODE REVIEW

**Comment by eshadatta** [comment]
@NYULibraries/hydra ,

Rebased branch. Thanks @da70 for the analysis of the merge.

**Comment by da70** [comment]
(Moved from old [#213](https://github.com/NYULibraries/ichabod/pull/213))

@eshadatta  Below are some notes on what I've looked at so far.  If I have time I can try and look at the rest.  Also, if these are changes you agree with, I'd be totally happy to do it as part of the user story Corey and I are pair-programming together ([#113569497](https://www.pivotaltracker.com/n/projects/1025368/stories/113569497)).
You've already done all the heavy lifting!  Much appreciated.

## As ActiveSupport::Concern

I didn't really know what these were so read about them a little.  They appear to be for reusing code amongst models.  Do we need this to be in more than one model?  At the moment it's used in `Nyucore` model, but also `Ichabod::ResourceSet::Resource`.  That being the case I wonder if we should just put the module in `lib/`, or else create a singleton object (an object for which the application only ever makes one instance) in the initializer called METADATA_FIELDS which in addition to the data from the YAML file would also containt the methods from the module.

## Naming: md -> metadata

Could we change:

* `md_fields.rb` -> `metadata_fields.rb`
* `module MdFields` -> `module MetadataFields`
* `get_md_fields.rb` -> `get_metadata_fields.rb`
* `MD_FIELDS` -> `METADATA_FIELDS`

Just for clarity and readability and also to keep consistent with YAML file name `metadata_fields.yml`?

## Module `md_fields.rb`

* Would suggest splitting `DEFAULT_VALUE = 'all'` into something like this:

```Ruby
NAMESPACE_ALL = 'all'
MULTIPLE_ALL  = 'all'

DEFAULT_NAMESPACE = NAMESPACE_ALL
DEFAULT_MULTIPLE  = MULTIPLE_ALL
```

This makes both param defaults individually configurable and also separates the options of "give me everything" and "give me whatever your default is, I don't care".  This could prevent bugs later if the default is changed from 'all' to something else for one or the other param.  (See below)

* Since `process_source_fields` and `parse_all_fields` basically do the same thing, might want to settle on just "parse" or "process" for both, or a different verb maybe.  Since this method mutates one of its arguments, it might be good to indicate that in the name (similarly to the Ruby convention of adding "!" to methods that mutate the object they are called on).  So maybe something like `add_all_fields( fields, multiple )` and `add_fields_for_namespace( fields, multiple, namespace )` - keeping the parameters list as parallel as possible for least surprise.  I think maybe it would be better to not use the word "source" in the method because that is Ichabod-specific, and we might want to re-use this elsewhere, or we might not use that "source" distinction forever.

* A suggested rewrite of this:

```Ruby
      if MD_FIELDS.has_key?(chk_key)
          process_source_fields(chk_key,multiple,fields)
      elsif ns == DEFAULT_VALUE 
          parse_all_fields(multiple,fields)
      end
```

...would be this:


```Ruby
      # Note we can't use `ns == DEFAULT_NAMESPACE` (or in original code, `ns == DEFAULT_VALUE`)
      # because there may come a time when DEFAULT_NAMESPACE (or DEFAULT_VALUE) are changed to
      # to something else besides 'all'.  The default could become 'nyucore', for example.
      if ns == NAMESPACE_ALL
          add_all_fields(fields, multiple)
      elsif METADATA_FIELDS.has_key?(chk_key)
          add_fields_for_namespace(fields, multiple, namespace)
      else
          # User has specified a namespace that is valid, but not present in the YAML file.
          # Either do nothing or raise an error or warning.
      end
```

* Suggested re-format, rewrite:

```Ruby
   output = multiple == DEFAULT_VALUE ? true : MD_FIELDS[ns][field][:multiple] == multiple
```

...to...

```Ruby
   output = ( multiple == NAMESPACE_ALL ) ?
                true :
                METADATA_FIELDS[ns][field][:multiple] == multiple
```

...just for readability.

**Comment by da70** [comment]
(Moved from old PR [#213|https://github.com/NYULibraries/ichabod/pull/213])

## `md_fields_spec.rg`

```Ruby
  	    context 'use of process_md_fields in an instance of a class' do
  	       subject { dummy_class.new }
  	       it { subject.should be_an_instance_of(dummy_class) }
  	       it { should respond_to(:process_md_fields) }
  	    end
```

* Typo: "in an instance of a class" -> "is an instance of a class"
* This assertion:
```Ruby
  	       subject { dummy_class.new }
  	       it { subject.should be_an_instance_of(dummy_class) }
```
...may not be necessary.  If I understand it correctly, the only way it can fail is if Ruby itself had a bug, or else if RSpec `subject` had a bug.
* Maybe it would be good to test the metadata fields in some additional ways:
** Number of namespaces and possibly their values
** Number of fields: total and/or per namespace, and possibly some or all of the values
** Structure of the fields: each field should have the required attributes.

Again, this is something Corey can do in the branch we've made off of yours if you need a break from this.

**Comment by eshadatta** [comment]
@da70 ,

Ah, I see you added feedback in the deleted PR. Thanks for that. I'll see if I can copy and paste them here. Thanks again.

**Comment by da70** [comment]
Oh, no worries.  I actually just copied and pasted them over.

**Comment by eshadatta** [comment]
@da70 , 
:+1: , Thanks, I'll look them over.

**Comment by eshadatta** [comment]
@da70 , @NYULibraries/hydra ,

About the use of the module in concerns:
I initially thought of just throwing a module in lib/ but didn't want lib/ to get more cluttered than it already was. It could be re-factored but let's table that for now as we have a pretty big re-factor of other things right now. The second reason is that, collection model can also use it as can other models...HIDVL and other input classes that could potentially be created. I also thought of initializing an object with the method in the initializer but I don't think that's considered very "rails-y". Eventually, though this is going to be a gem so, perhaps we shouldn't get too much into the weeds discussing it. I'm happy to reconsider if there's another solution or if the consensus is that we should keep it in lib/.

Sure, I can make the following changes:
1. Rename md to metadata
2. Reformat the output conditional statement
3. Make the default value changes you suggested
4. Split out the namespace and multiple functions for readability
5. Remove the instance assertion in rspec. I forgot to delete that.

I did think about checking the various combinations of the process_md_fields call to make sure we are getting the expected values. However, they are used in specs/models/nyucore_spec and in the resource rspecs and I thought to prevent duplication, it should be checked there and not in the module but perhaps they should be done in the module spec. I wanted to talk more about testing the module...perhaps in a tech meeting. 

 Thanks, I'll make the changes and submit a PR by the end of the day.

**Comment by da70** [comment]
Now that you've expounded on it, it actually does seem like this belongs with the models code, and since it might become a gem then yes it's moot at that point.  It's all nicely encapsulated now if we ever decide to move it it would be easy to do.

**Comment by eshadatta** [comment]
@NYULibraries/hydra , 
I made some of the changes as suggested by @da70 . Thanks again for looking it over.
These are the changes I made. 
1. Renamed md to metadata
2. Reformatted the output conditional statement
3. Made the suggested default value changes
4. Changed the private method names for better readability and changed the argument order
5. Removed the instance assertion in rspec
Thanks!

**Comment by eshadatta** [comment]
@da70 ,
Great, glad you agree about the models. Thanks.

**Comment by da70** [comment]
FYI, I found out why the Github branch comparisons for this PR were so different from what `git` reports:
Stackoverflow: [Github Comparison View for 2 branches is incorrect?|http://stackoverflow.com/questions/32570825/github-comparison-view-for-2-branches-is-incorrect]

Github uses `git diff A...B` instead of `git diff A..B` (3 dots instead of 2 dots).  This does a diff of the the common ancestor of A and B vs. current B.  In other words, it only shows what changed in branch B since diverged from A.  It does not show what is currently different between A and B.

**Pull request closed without merging**
