### PR TITLE
.travis.yml: updated Ruby versions and added comment describing versi…

### PR DESCRIPTION
**Pull request by da70**
…on test strategy

### CODE REVIEW

**Comment by eshadatta** [comment]
@da70 ,

If you want this to be merged, please flag someone for review. Just a fyi. @jgpawletko and others, are we good with moving the rvm versions up for testing on Travis? If so, let's merge this PR.

 Thanks.

**Comment by da70** [comment]
@eshadatta 
Sure, what's the procedure for flagging someone for review?  I wasn't aware there was an extra step after submitting the PR.  I figured once it was submitted, that you, Joe, or any of the other designated committers to main branches would review and merge.  Sorry for ignorance of protocol.

**Comment by eshadatta** [comment]
@da70 ,

No worries. Sorry, if this wasn't told to you earlier. The review is actually open to everyone in @NYULibraries/hydra. Flagging is just entering their handle and saying this is ready for review. Otherwise, it tends to gets ignored. Thanks!

**Comment by da70** [comment]
@eshadatta I see, so I should just add a comment "@person1, @person2 - PR is ready for review", or something like that.  Thanks.

**Comment by eshadatta** [comment]
Yup. Exactly

**Pull request merged**
