### PR TITLE
First draft of Nyucore readme

### PR DESCRIPTION
**Pull request by chrpr**
@jgpawletko @NYULibraries/hydra 

First cut at markdown file describing Nyucore and it's relationship to the Ichabod data model, Primo Normalized XML, and other potential formats.

Feedback encouraged & PR's to my branch welcome!

### CODE REVIEW

**Comment by jgpawletko** [comment]
@chrpr 
Thank you for putting this together.
A couple of comments:
* you might want to use the word "Primo" as the anchor text for a link to a page that explains what Primo is, or prefix "Primo" with "Ex Libris' " (in case folks know nothing about Primo)
* the links in the **Field Definitions** section didn't work for me...  I think you need to make the paths relative, e.g., `lib/nyucore_metadata/vocabulary.rb` becomes `../../lib/nyucore_metadata/vocabulary.rb`.
More info [here](https://help.github.com/articles/relative-links-in-readmes/).
* the `This` in `TODO: This should...` is ambiguous to me.  Do you mean `Collection`?

**Comment by chrpr** [comment]
Thanks @jgpawletko!

I think I've addressed all of your suggestions. 

@NYULibraries/hydra If there's any other feedback, please share soon. I'd like to get this merged in the next day or 2 so that folks can link to it in the Open Repositories slides if desired.

Cheers,
-Corey

**Comment by eshadatta** [comment]
@chrpr , I think this is a good first draft. I'm sure we'll iterate as we move forward but I believe it explains things as they are. Perhaps in a later draft, we can clarify things as to why some fields are in the Ichabod  vocabulary vs Nyucore. Thanks.

**Comment by chrpr** [comment]
@eshadatta Good call, Esha. I'd already mentioned Administrative for the Ichabod Vocabulary, but some of those other distinctions just emerged from yesterday's meeting. Latest commit tries to capture this distinction, and also adds a placeholder for the Collection level model and datastreams.

Let me know if this addresses your suggestion.

Thanks!

**Comment by eshadatta** [comment]
@chrpr , thanks, looks good to me.

**Pull request merged**
